### ISSUE TITLE
When clicking on building, info box appears in upper left corner

### ISSUE THREAD

**Issue by JLSievert** [grasbrook-cityscope/functionalscope#70] opened 2021-10-01 09:06 UTC
When clicking on a building, the info box should appear next to the building. Now, the first time you click on a building, the info box appears in the upper lefthand corner.

![grafik](https://user-images.githubusercontent.com/45463490/135594766-a020ae07-a1d6-45db-a8d9-402a3ba0bbf5.png)

**Comment by totev** [comment] 2021-10-01 09:07
Duplicate of #66

**Closed by totev** 2021-10-01 09:07 UTC
Labels: bug
